### ISSUE TITLE
Firejail role fails: "Destination /etc/firejail/firejail.users does not exist"

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#114]
```
TASK [firejail : Add user to firejail users] ************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Destination /etc/firejail/firejail.users does not exist !", "rc": 257}
```

Error is the result of this particular task

```
- name: Add user to firejail users
  lineinfile:
    dest: /etc/firejail/firejail.users
    state: present
    line: "{{ user.name }}"
```

I think that the reason is in fact that firejail package doesn't contain `/etc/firejail/firejail.users`

```
❯ yay -Ql firejail | grep user
firejail /etc/firejail/login.users
firejail /etc/firejail/whitelist-runuser-common.inc
firejail /usr/share/man/man5/firejail-users.5.gz
```
