### ISSUE TITLE
Installation of AUR packages started before user is added to sudoers.

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#117]
There is a [task](https://github.com/pigmonkey/spark/blob/master/roles/base/tasks/packages.yml#L30C1-L36C15) in base 

```
- name: Install AUR base packages
  aur:
    name: "{{ aur.packages }}"
    user: "{{ user.name }}"
  tags:
    - aur
    - packages
```

On fresh install, it fails with the error in title of issue. The reason is in fact that sudo role runs after base role.

P.S. The temporary workaround is to run sudo role after fail and run whole playbook again.
