### ISSUE TITLE
SSH: enable ssh agent

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#118]
Arch wiki in section [Start ssh-agent with systemd user](https://wiki.archlinux.org/title/SSH_keys#Start_ssh-agent_with_systemd_user) proposes:

> If you would like your ssh agent to run when you are logged in, regardless of whether X is running, a handy ssh-agent.service is included in [openssh](https://archlinux.org/packages/?name=openssh) since the version 9.4p1-3, which can be [enabled](https://wiki.archlinux.org/title/Enabled) as a [user unit](https://wiki.archlinux.org/title/User_unit).

So maybe it is useful to add something like this in ssh role:

```
- name: Enable ssh-agent service
  service:
    name: ssh-agent.service
    enabled: yes
    state: started
    scope: user
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
```
