### ISSUE TITLE
Moving some personal variables to separate file

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#124]
Right now, there is a collection of personal variables like these:

```
    name: pigmonkey
    group: pigmonkey
    email: peter@havenaut.net

#...

network:
    conn_check: False
    trusted_uuid:
        - 39744b35-2f2f-4a18-9da4-7542a56c28c2
```

On one hand, this poses a privacy violation for individuals who publish or keep track of changes to their version of this repository. On the other hand, it is often useless for other users, as they typically have their own usernames, dotfiles, or trusted networks.

My proposal is as follows:
- Move personal variables to a separate variable file.
- Add this file to `.gitignore`.
- Create a template for it with examples (e.g., `personal.template`).
