### ISSUE TITLE
sshd config, some notes

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#30]
`AllowTcpForwarding`:

Qutation from `man sshd_config`:

> The default is “yes”.  Note that disabling TCP forwarding does not improve security unless users are also denied shell access, as they can always install their own forwarders

So probably it isn't necessary for setting it to `no` value.

And also could you please explain why you use this very Ciper: `aes256-ctr` and MACs: `hmac-sha2-512`. Why these and not something else (default for example).

**Comment by petRUShka** [comment]
And also why fuse configuration in sshd block?

**Comment by pigmonkey** [comment]
My memory is that the cipher and MAC came from [Mozilla's guide](https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Modern_.28OpenSSH_6.7.2B.29), but I don't recall why we settled on one each. I don't use SSHD on my laptop, so this is a corner of Spark I don't often peer into. I think updating the config to Mozilla's current recommendations are fine.

The Fuse configuration is needed for autossh. It could be split out into it's own role that the SSH role depends on, but that would be a role with a single task which seems unecessary since I don't think we have anything else that would depend on it.

Good point on the TCP forwarding. We're setting `AllowUsers` and disabling password auth, so there's probably no reason to disable forwading.

**Comment by petRUShka** [comment]
Thanks for detailed answer. What do you think is it worth to mention in comment that you are based on Mozilla's guide?

And another question. What do you think about moving from replacing sshd config to assuring that certain options are set to certain values and other are arch default. I mean something like this:

```
- name: Push OpenSSH daemon configuration file
  lineinfile: dest=/etc/ssh/sshd_config
              state=present
              insertafter="^{{ item.param }}"
              line="{{ item.param }} {{ item.value }}"
  with_items:
    - { param: "X11Forwarding", value: "yes"}
    - { param: "PermitRootLogin", value: "no"}
    - { param: "Protocol", value: "2"}
    - { param: "PasswordAuthentication", value: "no"}
    - { param: "AllowUsers", value: "{{ user.name }}"}
    - { param: "Ciphers", value: "aes256-ctr"}
```
