### ISSUE TITLE
Firejailed browsers dpends on xdg user dirs, which don't exist

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#45]
Browser (Firefox, Chromium) default profiles include following line:

```
whitelist ${DOWNLOADS}
```

so it depends on existance of `${DOWNLOADS}` dir. Otherwise you cannot actually download files with jailed browsers. Downloads folder is one of the [XDG user dirs](https://wiki.archlinux.org/index.php/XDG_user_directories).

I propose to add following lines to `x` role:

```YAML
- name: Install xdg-user-dirs 
  pacman: name=xdg-user-dirs state=present

- name: Create user directories
  shell: LC_ALL=C /usr/bin/xdg-user-dirs-update
  args:
    creates: /home/{{ user.name }}/Downloads 
  become: "{{ user.name }}"
```
Instead of `LC_ALL=C` one may place some configurable locale. Possibly somebody wants to have localized xdg dirs.
